### ISSUE TITLE
Is this plugin webpack 4 compatible?

### ISSUE THREAD

**Issue by et** [quackes/webpack-encoding-plugin#5]
I tried to use this on my webpack 4 build and it seemed to make all the special characters question marks.

**Comment by irudoy** [comment]
Same issue with webpack@4.5.0

**Comment by Morjodrom** [comment]
The plugin does work with webpack@4.21.0 in my environment. But I must remind, that webpack dev server must be configured to pass charset headers: 
``` JavaScript
devServer:  {
   headers: {
      'Access-Control-Allow-Origin': '*',
      'Content-Type': 'application/javascript; charset=windows-1251'
   }
   // ...
}
```

**Comment by quackes** [comment]
please retry with the new version. a a lot has been changed.
The Plugin was refactored to new Webpack 4.x plugin architecture. (thanks to @irudoy)

Please open a new issue, if the problem persists.

Thank you :)
