### ISSUE TITLE
I can't use it in webpack4.12.0

### ISSUE THREAD

**Issue by LiangJunrong** [quackes/webpack-encoding-plugin#6]
I try to set the encoding "utf-8" to "gb2312", but it didn't run.
the same as my project address:https://github.com/LiangJunrong/webpack-question.
please help me, thanks.

**Comment by quackes** [comment]
@LiangJunrong  please retry with the new version. a a lot has been changed.
The Plugin was refactored to new Webpack 4.x plugin architecture.

Please open a new issue, if the problem persists.

Thank you :)
