### ISSUE TITLE
encode iso-8859-1 not work on firefox

### ISSUE THREAD

**Issue by ruannawe** [quackes/webpack-encoding-plugin#7]
[Image with error](https://ibb.co/kH76jJ)
```js
    var EncodingPlugin = require('webpack-encoding-plugin')
    ...
    plugins: [new EncodingPlugin({
        encoding: 'iso-8859-1'
    })],
```

**Comment by quackes** [comment]
@RuanHerculano please retry with the new version. a a lot has been changed.

Please open a new issue, if the problem persists.

Thank you :)
